@startuml

abstract class Note {
+ Complete()
+ Start()
+ ChangeParent()
- name: String
- description: String
- short_name: String
- parent: Note
- status: NoteStatus
}

class Aspect {
+ Add(Note)
- bar: int
- children: Note[]
}

class Todo {
...
}

class Task {
...
}

class Project {
...
}

Aspect o--> Note
Note <|-- Aspect
Aspect <|-- Project
Project <|-- Task
Note <|-- Todo

@enduml